export const GET_HOME_PAGE_INFORMATION = 'GET_HOME_PAGE_INFORMATION'

export const GET_PICTURES_BY_DATE = 'GET_PICTURES_BY_DATE'

export const GET_PLANT_INFO = 'GET_PLANT_INFO'

export const GET_NEW_DATA = 'GET_NEW_DATA'

export const REQUEST_BEGIN = 'REQUEST_BEGIN'

export const REQUEST_FINISH = 'REQUEST_FINISH'
